### PR TITLE
Added standard Travis config

### PR DESCRIPTION
**Pull request by helpfulrobot**
Hello!

I'm helpful robot. I noticed you had some non-standard Travis config. I think this is an improvement.

Have a nice day! [f-f-f-f-f-f-t]

### CODE REVIEW

**Comment by tractorcow** [comment]
Oh right, so that's why queuedjobs and subsites tests no longer run...

**Comment by dhensby** [comment]
wups

**Comment by assertchris** [comment]
Dammit, stupid robot. If one of you is close to it, please give it a clip about the ears...

**Comment by tractorcow** [comment]
I blame the parents!

**Pull request merged**
