### PR TITLE
DEP Use the canonical repository for proxy-db

### PR DESCRIPTION
**Pull request by GuySartorelli**
Requires https://github.com/tractorcow/silverstripe-proxy-db/pull/6 to be merged and tagged

## Parent issue
- https://github.com/silverstripeltd/product-issues/issues/658

### CODE REVIEW

**Review by emteknetnz — APPROVED** [review]
Approved but don't merge until https://github.com/tractorcow/silverstripe-proxy-db/pull/6 is merged

**Comment by emteknetnz** [comment]
@GuySartorelli can you re push this to get a new build to run

**Comment by GuySartorelli** [comment]
@emteknetnz I can but shouldn't we wait for proxy-db to be tagged stable?

**Comment by GuySartorelli** [comment]
Rebased on `4.0`

**Review by michalkleiner — APPROVED** [review]

**Pull request merged**
